### ISSUE TITLE
TASK LIST

### ISSUE THREAD

**Issue by code-monk08** [code-monk08/WordpressTwitterBot#1]
- [ ] FIND WORDPRESS API

- [ ] TRY READING A WORDPRESS BLOG AND IT’S ARTICLE USING THAT API, THIS API RESULTS IN JSON DATA

- [ ] FOR EVERY ARTICLE FIND ASSOCIATED GIFS & CHARTS

- [ ] MAKE NLTK SUMMARIZER USING ARTICLE TEXT IN JSON DATA 

- [ ] MAKE A SUMMARY + ATTACH IMAGES/GIF/CHARTS

- [ ] MAKE A TWITTER BOT WHICH POSTS TWEETS OF THOSE IMAGES ADDED SUMMARIES.

- [ ] ADDITIONAL FEATURE INSIDE THE BOT :  RESPOND TWEET 

- [ ] IF SOME ONE MENTIONS THE BOT, AND IS TALKING ABOUT SOME RESEARCH PAPER/ ARTICLE THE BOT MUST SUMMARIZE THAT PARTICULAR ARTICLE AND SHOULD COMMENT THE SUMMARY IN THAT TWEET!
